set(_CATKIN_CURRENT_PACKAGE "capture_key")
set(capture_key_MAINTAINER "gaetan <gaetan@todo.todo>")
set(capture_key_DEPRECATED "")
set(capture_key_VERSION "0.0.0")
set(capture_key_BUILD_DEPENDS "roscpp" "std_msgs")
set(capture_key_RUN_DEPENDS "roscpp" "std_msgs")
set(capture_key_BUILDTOOL_DEPENDS "catkin")