set(_CATKIN_CURRENT_PACKAGE "socket_baxter2oculus")
set(socket_baxter2oculus_MAINTAINER "towardthesea <ph17dn@gmail.com>")
set(socket_baxter2oculus_DEPRECATED "")
set(socket_baxter2oculus_VERSION "0.0.0")
set(socket_baxter2oculus_BUILD_DEPENDS "roscpp" "std_msgs" "sensor_msgs" "baxter_core_msgs" "cmake_modules")
set(socket_baxter2oculus_RUN_DEPENDS "cmake_modules" "roscpp" "std_msgs" "sensor_msgs" "baxter_core_msgs")
set(socket_baxter2oculus_BUILDTOOL_DEPENDS "catkin")